"""empty message

Revision ID: 0518587ed710
Revises: d6232ab3b7e9
Create Date: 2020-03-10 19:40:06.011814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0518587ed710'
down_revision = 'd6232ab3b7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_asset_storage',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('data_storage_location_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['data_storage_location_id'], ['data_storage_location.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'data_storage_location_id')
    )
    op.drop_table('DigitalAssetStorage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DigitalAssetStorage',
    sa.Column('asset_id', sa.INTEGER(), nullable=False),
    sa.Column('data_storage_location_id', sa.INTEGER(), nullable=False),
    sa.Column('uri', sa.VARCHAR(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['data_storage_location_id'], ['data_storage_location.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'data_storage_location_id')
    )
    op.drop_table('digital_asset_storage')
    # ### end Alembic commands ###
