"""empty message

Revision ID: 7c4276181267
Revises: 
Create Date: 2020-03-22 19:56:18.660105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4276181267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_data_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_data_provider_name'), 'storage_data_provider', ['name'], unique=True)
    op.create_table('digital_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_asset_name'), 'digital_asset', ['name'], unique=False)
    op.create_index(op.f('ix_digital_asset_type'), 'digital_asset', ['type'], unique=False)
    op.create_table('storage_data_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('continent', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['data_provider_id'], ['storage_data_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_data_location_continent'), 'storage_data_location', ['continent'], unique=False)
    op.create_index(op.f('ix_storage_data_location_country'), 'storage_data_location', ['country'], unique=False)
    op.create_index(op.f('ix_storage_data_location_name'), 'storage_data_location', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('digital_asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('details', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_asset',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('data_storage_location_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['data_storage_location_id'], ['storage_data_location.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'data_storage_location_id')
    )
    op.create_table('storage_asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_storage_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['data_storage_location_id'], ['storage_data_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_asset_history')
    op.drop_table('storage_asset')
    op.drop_table('digital_asset_history')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_storage_data_location_name'), table_name='storage_data_location')
    op.drop_index(op.f('ix_storage_data_location_country'), table_name='storage_data_location')
    op.drop_index(op.f('ix_storage_data_location_continent'), table_name='storage_data_location')
    op.drop_table('storage_data_location')
    op.drop_index(op.f('ix_digital_asset_type'), table_name='digital_asset')
    op.drop_index(op.f('ix_digital_asset_name'), table_name='digital_asset')
    op.drop_table('digital_asset')
    op.drop_index(op.f('ix_storage_data_provider_name'), table_name='storage_data_provider')
    op.drop_table('storage_data_provider')
    op.drop_table('organisation')
    # ### end Alembic commands ###
