"""empty message

Revision ID: e0e8e7232614
Revises: 
Create Date: 2020-03-31 19:31:06.567636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e8e7232614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('ind_fragile_state_index', sa.String(length=10), nullable=True),
    sa.Column('ind_ict_dev_index', sa.String(length=10), nullable=True),
    sa.Column('ind_hdi', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    op.create_table('format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_data_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ind_current_ratio', sa.String(length=10), nullable=True),
    sa.Column('ind_quick_ratio', sa.String(length=10), nullable=True),
    sa.Column('ind_return_on_assets', sa.String(length=10), nullable=True),
    sa.Column('ind_accounts_receivable_turnover_ratio', sa.String(length=10), nullable=True),
    sa.Column('ind_operating_cash_flow_ratio', sa.String(length=10), nullable=True),
    sa.Column('ind_pretax_net_profit_margin', sa.String(length=10), nullable=True),
    sa.Column('ind_inventory_turnover', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_data_provider_name'), 'storage_data_provider', ['name'], unique=True)
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_data_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['data_provider_id'], ['storage_data_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('digital_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['format_id'], ['format.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id')
    )
    op.create_table('digital_asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('details', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_asset',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('data_storage_location_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['data_storage_location_id'], ['storage_data_location.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'data_storage_location_id')
    )
    op.create_table('storage_asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_storage_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['data_storage_location_id'], ['storage_data_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_asset_history')
    op.drop_table('storage_asset')
    op.drop_table('digital_asset_history')
    op.drop_table('storage_strategy')
    op.drop_table('digital_asset')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('storage_data_location')
    op.drop_table('collection')
    op.drop_index(op.f('ix_storage_data_provider_name'), table_name='storage_data_provider')
    op.drop_table('storage_data_provider')
    op.drop_table('organisation')
    op.drop_table('format')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
