"""empty message

Revision ID: f18ff36bd342
Revises: e0e8e7232614
Create Date: 2020-04-04 12:44:27.300002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18ff36bd342'
down_revision = 'e0e8e7232614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_data_provider', sa.Column('description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_data_provider', 'description')
    # ### end Alembic commands ###
